# Try and find lib and bin folders locally.

IF(NOT FOUND_OUTPUT_DIRECTORY_ROOT)
	GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/bin ABSOLUTE)
	IF(NOT IS_DIRECTORY ${OUTPUT_DIRECTORY_ROOT})
		#MESSAGE(STATUS "Not ${OUTPUT_DIRECTORY_ROOT}")
		GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/../../bin ABSOLUTE)
		IF(NOT IS_DIRECTORY ${OUTPUT_DIRECTORY_ROOT})
			#MESSAGE(STATUS "Not ${OUTPUT_DIRECTORY_ROOT}")
			GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/../../../bin ABSOLUTE)
			IF(IS_DIRECTORY ${OUTPUT_DIRECTORY_ROOT})
				GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/../../../ ABSOLUTE)
				SET(FOUND_OUTPUT_DIRECTORY_ROOT 1)
			ELSE()
				#MESSAGE(STATUS "Failed")
				SET(OUTPUT_DIRECTORY_ROOT ${CMAKE_BINARY_DIR})
			ENDIF()
		ELSE()
			GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/../../ ABSOLUTE)
			SET(FOUND_OUTPUT_DIRECTORY_ROOT 1)
		ENDIF()
	ELSE()
		GET_FILENAME_COMPONENT(OUTPUT_DIRECTORY_ROOT ${CMAKE_SOURCE_DIR}/ ABSOLUTE)
		SET(FOUND_OUTPUT_DIRECTORY_ROOT 1)
	ENDIF()
	#MESSAGE(STATUS "Binary Output Path: ${OUTPUT_ROOT_DIR}")
ENDIF()

SET(OUTPUT_DIRECTORY_ROOT ${OUTPUT_DIRECTORY_ROOT} CACHE PATH "Root output folder for binaries." )

IF(NOT OUTPUT_DIRECTORY_ROOT)
	SET(OUTPUT_DIRECTORY_ROOT ${CMAKE_BINARY_DIR})
ENDIF()

IF(WIN32)
SET(CPACK_NSIS_INSTALL_ROOT  "C:\\\\UCF")
#MESSAGE(STATUS "CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}")
ENDIF(WIN32)

# Set output folders for binaries and libraries.
#MESSAGE(STATUS "${OUTPUT_DIRECTORY_ROOT}/bin")
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY_ROOT}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_ROOT}/bin)
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_ROOT}/bin)
IF(WIN32)
	# Make sure DLL files are in the same directory as executeables in Windows
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY_ROOT}/bin)
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_ROOT}/bin)
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_ROOT}/bin)
ELSE()
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY_ROOT}/lib)
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_ROOT}/lib)
	SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_ROOT}/lib)
ENDIF(WIN32)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_DIRECTORY_ROOT}/lib)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${OUTPUT_DIRECTORY_ROOT}/lib)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${OUTPUT_DIRECTORY_ROOT}/lib)

link_directories(${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
					${CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG}
					${CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE}
					${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
					${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG}
					${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE})

# In other systems besides MSVC, a lib prefix is
# added to all 
IF(MSVC)
	SET(LIB_PREFIX "lib")
ELSE()
	SET(LIB_PREFIX "")
ENDIF(MSVC)


